export { default as Home } from './home/home'
export { default as News } from './blog/news'
export { default as Preventions } from './prevention/tips'
export { default as Locations } from './post/locations'
export { default as About } from './about/about'
export { default as Settings } from './config/menu'
