export { default as HomeIndex } from './home/homeindex'
export { default as NewsIndex } from './blog/newsindex'
export { default as PostIndex } from './post/localindex'
export { default as PreventionIndex } from './prevention/avoidindex'
export { default as AboutIndex } from './about/aboutindex'
export { default as SettingsScreen } from './config/settingsindex'
